theme: "starter-hugo-academic"
# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: Harrison Yongjoon Youn # Website name
baseURL: 'https://www.harrisonyoun.com/' # Website URL

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## MODULES
############################

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5

############################
## ADVANCED
############################


enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  event: '/talk/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 85
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
  
############################
## MATH SUPPORT
############################
math:
  enable: true
  engine: MathJax
  
############################
## THEME CUSTOMIZATIONS
############################

theme_customizations:
  homepage:
    show_posts: false # Disable blog posts for a cleaner homepage
    hero_section:
      image_size: large
      text_align: center
      max_width: 600px # Reduced max width for a more focused look
  header:
    show_search: false # Removed search bar for simplicity
    align: r
    show_logo: false # Removed logo for a cleaner header
  footer:
    minimal_footer: true # Set footer to minimal to keep it professional
  research_page:
    view: list
    columns: 1 # Display working papers as a single-column list for clarity
    show_download_links: true # Add PDF download links for easy access

avatar:
  gravatar: false
  shape: circle
  size: large # Increased the avatar size for prominence

############################
## EXTENSIONS
############################

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: false
  css:
    custom_css: ["css/reveal_custom.css"]
  privacy_pack:
    enable: false # Disable privacy features for simplicity
