# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  theme_day: Minimal
  theme_night: Minimal
  font: native
  font_size: m


# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Researcher in Economics focusing on labor, health, and aging.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: 'google-site-verification=X0LQ9NpJIqseg-YdvoT_VQ3v6ctopsgWS7By_xTowSA'

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: false
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Harrison Youn. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/YongjoonYoun/homepage'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: square
    size: large
  comment:
    provider: ''
  search:
    provider: wowchemy
  map:
    provider: ''

# Extensions
extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: false
  css:
    custom_css: ["css/reveal_custom.css"]
    
# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true

############################
## THEME CUSTOMIZATIONS
############################

homepage:
  show_posts: false # Disable blog posts on the homepage
  hero_section:
    image_size: large # Increase profile picture size
    text_align: center
    max_width: 800px
    align: center # Add this to ensure the hero section content (avatar + text) is centered
    layout: "vertical" # This helps ensure the avatar is above the text
research_page:
  view: list
  columns: 1 # Display working papers as a list for clarity
  show_download_links: true # Add PDF download links for each paper


